// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "Reserva-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // Reserva
  //

  const char alias_traits<  ::usuari,
    id_mysql,
    access::object_traits_impl< ::Reserva, id_mysql >::usuari_tag>::
  table_name[] = "`usuari_username`";

  struct access::object_traits_impl< ::Reserva, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::Reserva, id_mysql >::id_type
  access::object_traits_impl< ::Reserva, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        id,
        i._idReserva_value,
        i._idReserva_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Reserva, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _idReserva
    //
    t[0UL] = 0;

    // _dataReserva
    //
    t[1UL] = 0;

    // _numPlaces
    //
    t[2UL] = 0;

    // _preuPagat
    //
    t[3UL] = 0;

    // _usuari
    //
    if (t[4UL])
    {
      i._usuari_value.capacity (i._usuari_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::Reserva, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // _idReserva
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i._idReserva_value;
      b[n].is_null = &i._idReserva_null;
      n++;
    }

    // _dataReserva
    //
    b[n].buffer_type = MYSQL_TYPE_DATE;
    b[n].buffer = &i._dataReserva_value;
    b[n].is_null = &i._dataReserva_null;
    n++;

    // _numPlaces
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i._numPlaces_value;
    b[n].is_null = &i._numPlaces_null;
    n++;

    // _preuPagat
    //
    b[n].buffer_type = MYSQL_TYPE_FLOAT;
    b[n].buffer = &i._preuPagat_value;
    b[n].is_null = &i._preuPagat_null;
    n++;

    // _usuari
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._usuari_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._usuari_value.capacity ());
    b[n].length = &i._usuari_size;
    b[n].is_null = &i._usuari_null;
    n++;
  }

  void access::object_traits_impl< ::Reserva, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Reserva, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // _idReserva
    //
    if (sk == statement_insert)
    {
      int const& v =
        o._idReserva;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i._idReserva_value, is_null, v);
      i._idReserva_null = is_null;
    }

    // _dataReserva
    //
    {
      ::boost::gregorian::date const& v =
        o._dataReserva;

      bool is_null (true);
      mysql::value_traits<
          ::boost::gregorian::date,
          mysql::id_date >::set_image (
        i._dataReserva_value, is_null, v);
      i._dataReserva_null = is_null;
    }

    // _numPlaces
    //
    {
      int const& v =
        o._numPlaces;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i._numPlaces_value, is_null, v);
      i._numPlaces_null = is_null;
    }

    // _preuPagat
    //
    {
      float const& v =
        o._preuPagat;

      bool is_null (false);
      mysql::value_traits<
          float,
          mysql::id_float >::set_image (
        i._preuPagat_value, is_null, v);
      i._preuPagat_null = is_null;
    }

    // _usuari
    //
    {
      ::std::shared_ptr< ::usuari > const& v =
        o._usuari;

      typedef object_traits< ::usuari > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::usuari > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& ptr_id (
          obj_traits::id (ptr_traits::get_ref (v)));

        std::size_t size (0);
        std::size_t cap (i._usuari_value.capacity ());
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_string >::set_image (
          i._usuari_value,
          size,
          is_null,
          ptr_id);
        i._usuari_null = is_null;
        i._usuari_size = static_cast<unsigned long> (size);
        grew = grew || (cap != i._usuari_value.capacity ());
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::Reserva, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _idReserva
    //
    {
      int& v =
        o._idReserva;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i._idReserva_value,
        i._idReserva_null);
    }

    // _dataReserva
    //
    {
      ::boost::gregorian::date& v =
        o._dataReserva;

      mysql::value_traits<
          ::boost::gregorian::date,
          mysql::id_date >::set_value (
        v,
        i._dataReserva_value,
        i._dataReserva_null);
    }

    // _numPlaces
    //
    {
      int& v =
        o._numPlaces;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i._numPlaces_value,
        i._numPlaces_null);
    }

    // _preuPagat
    //
    {
      float& v =
        o._preuPagat;

      mysql::value_traits<
          float,
          mysql::id_float >::set_value (
        v,
        i._preuPagat_value,
        i._preuPagat_null);
    }

    // _usuari
    //
    {
      ::std::shared_ptr< ::usuari >& v =
        o._usuari;

      typedef object_traits< ::usuari > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::usuari > > ptr_traits;

      if (i._usuari_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_string >::set_value (
          ptr_id,
          i._usuari_value,
          i._usuari_size,
          i._usuari_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (ptr_id));
      }
    }
  }

  void access::object_traits_impl< ::Reserva, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Reserva, id_mysql >::persist_statement[] =
  "INSERT INTO `Reserva` "
  "(`idReserva`, "
  "`dataReserva`, "
  "`numPlaces`, "
  "`preuPagat`, "
  "`usuari_username`) "
  "VALUES "
  "(?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Reserva, id_mysql >::find_statement[] =
  "SELECT "
  "`Reserva`.`idReserva`, "
  "`Reserva`.`dataReserva`, "
  "`Reserva`.`numPlaces`, "
  "`Reserva`.`preuPagat`, "
  "`Reserva`.`usuari_username` "
  "FROM `Reserva` "
  "WHERE `Reserva`.`idReserva`=?";

  const char access::object_traits_impl< ::Reserva, id_mysql >::update_statement[] =
  "UPDATE `Reserva` "
  "SET "
  "`dataReserva`=?, "
  "`numPlaces`=?, "
  "`preuPagat`=?, "
  "`usuari_username`=? "
  "WHERE `idReserva`=?";

  const char access::object_traits_impl< ::Reserva, id_mysql >::erase_statement[] =
  "DELETE FROM `Reserva` "
  "WHERE `idReserva`=?";

  const char access::object_traits_impl< ::Reserva, id_mysql >::query_statement[] =
  "SELECT\n"
  "`Reserva`.`idReserva`,\n"
  "`Reserva`.`dataReserva`,\n"
  "`Reserva`.`numPlaces`,\n"
  "`Reserva`.`preuPagat`,\n"
  "`Reserva`.`usuari_username`\n"
  "FROM `Reserva`\n"
  "LEFT JOIN `usuari` AS `usuari_username` ON `usuari_username`.`username`=`Reserva`.`usuari_username`";

  const char access::object_traits_impl< ::Reserva, id_mysql >::erase_query_statement[] =
  "DELETE FROM `Reserva`";

  const char access::object_traits_impl< ::Reserva, id_mysql >::table_name[] =
  "`Reserva`";

  void access::object_traits_impl< ::Reserva, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Reserva, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Reserva, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Reserva, id_mysql >::pointer_type
  access::object_traits_impl< ::Reserva, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Reserva, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Reserva, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Reserva, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Reserva, id_mysql >::object_type >
  access::object_traits_impl< ::Reserva, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Reserva, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
