/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Experiencia`;

CREATE TABLE `Experiencia` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(128) NOT NULL,
  `nom` TEXT NOT NULL,
  `preu` DOUBLE NOT NULL)
 ENGINE=InnoDB;

