/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Reserva`;

CREATE TABLE `Reserva` (
  `idReserva` INT NOT NULL PRIMARY KEY,
  `dataReserva` DATE NULL,
  `numPlaces` INT NOT NULL,
  `preuPagat` FLOAT NOT NULL,
  `usuari` VARCHAR(128) NOT NULL,
  `experiencia` VARCHAR(128) NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `Reserva`
  ADD CONSTRAINT `Reserva_usuari_fk`
    FOREIGN KEY (`usuari`)
    REFERENCES `usuari` (`username`)
    ON DELETE CASCADE,
  ADD CONSTRAINT `Reserva_experiencia_fk`
    FOREIGN KEY (`experiencia`)
    REFERENCES `Experiencia` (`nom`)
*/

